name: 'HackLintTest'
description: 'Runs the Hack typechecker, linter (HHAST) and tests (HackTest)'
inputs:
  hhvm:
    description: 'HHVM version (latest/nightly/#.##)'
    required: true
  skip_lint:
    description: 'Optional. Set to "true" to skip the hhast-lint step.'
    required: false
    default: false
  skip_tests:
    description: 'Optional. Set to "true" to skip the hacktest step.'
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - name: Install Composer
      shell: bash
      run: ${{github.action_path}}/install-composer.sh --install-dir=${{runner.temp}}
    - name: Install HHVM
      shell: bash
      run: ${{github.action_path}}/install-hhvm.sh ${{inputs.hhvm}}
    - name: Inspect HHVM and Hack versions
      shell: bash
      run: |
        hhvm --version
        hh_client --version
    - name: Install project dependencies
      shell: bash
      run: |
        echo "::group::Install project dependencies"
        php ${{runner.temp}}/composer.phar install
        echo "::endgroup::"
    - name: Typecheck
      shell: bash
      run: |
        echo "::group::Typecheck"
        hh_client
        echo "::endgroup::"
    - name: Lint
      shell: bash
      run: ${{github.action_path}}/lint.sh "${{inputs.hhvm}}" "${{inputs.skip_lint}}"
    - name: Run tests
      shell: bash
      run: ${{github.action_path}}/test.sh "${{inputs.skip_tests}}"
